# Disable all lint rules to remove blue underlines
analyzer:
  errors:
    # Treat all warnings and hints as ignore
    todo: ignore
    hint: ignore
    warning: ignore
    lint: ignore

linter:
  rules: []
