name: cafeshop
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  provider: ^6.1.5
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  firebase_core: ^4.0.0
  google_sign_in: ^7.1.1
  firebase_auth: ^6.0.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/coffee_shop_bg.png"


flutter_native_splash:
  color: "#ffffff"         # background color (white in this example)
  image: assets/images/coffee_shop_logo.png
  android: true
  ios: true
  web: false


flutter:
  uses-material-design: true

  assets:
    - assets/images/cupofcoffee.png
    - assets/images/coffeedecoration.png
    - assets/images/cofffeeimagetop.png
    - assets/images/coffeebeans.png 
    - assets/images/brownhearts.png
    - assets/images/image.png
    - assets/images/coffeedisplay.jpg
    - assets/images/coffee_shop_logo.png
    - assets/images/coffee_shop_bg.png
    - assets/images/profile_placeholder.png
    - assets/images/onboard.png
    - assets/images/courier.jpg
    - assets/images/coffee1.jpg
    - assets/images/coffee2.jpg
    - assets/images/coffee3.jpg
    - assets/images/coffee4.jpg
    - assets/icons/google.svg
