// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaSS00_9XY1oxM3xP1mp4kOyhAqOSxCUU',
    appId: '1:810863252771:web:8ad55beda1dceca2972896',
    messagingSenderId: '810863252771',
    projectId: 'coffee-shop-app0323',
    authDomain: 'coffee-shop-app0323.firebaseapp.com',
    storageBucket: 'coffee-shop-app0323.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ZTuUi-hVw27ywurkwXU_viVrhpG1UmE',
    appId: '1:810863252771:android:7abc7fa167a6f21f972896',
    messagingSenderId: '810863252771',
    projectId: 'coffee-shop-app0323',
    storageBucket: 'coffee-shop-app0323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZNIRqKVgwK61BHW63DA_7yEbTtW34IfY',
    appId: '1:810863252771:ios:b04de2e05825996c972896',
    messagingSenderId: '810863252771',
    projectId: 'coffee-shop-app0323',
    storageBucket: 'coffee-shop-app0323.firebasestorage.app',
    iosBundleId: 'com.example.cafeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZNIRqKVgwK61BHW63DA_7yEbTtW34IfY',
    appId: '1:810863252771:ios:b04de2e05825996c972896',
    messagingSenderId: '810863252771',
    projectId: 'coffee-shop-app0323',
    storageBucket: 'coffee-shop-app0323.firebasestorage.app',
    iosBundleId: 'com.example.cafeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaSS00_9XY1oxM3xP1mp4kOyhAqOSxCUU',
    appId: '1:810863252771:web:34139345bc927567972896',
    messagingSenderId: '810863252771',
    projectId: 'coffee-shop-app0323',
    authDomain: 'coffee-shop-app0323.firebaseapp.com',
    storageBucket: 'coffee-shop-app0323.firebasestorage.app',
  );
}
